// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// exportBeeConstants
void exportBeeConstants();
RcppExport SEXP beer_exportBeeConstants() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    exportBeeConstants();
    return R_NilValue;
END_RCPP
}
